version: "2"

services:
  # .NET server
  dotnet:
    container_name: "stata_dotnet"
    image: stata/dotnet
    ports:
      - "9090:9090"
    network_mode: "host"

  # j2e server
  j2e:
    container_name: "stata_j2e"
    image: stata/j2e
    ports:
      - "8080:8080"
    network_mode: "host"
